platform :ios, '8.0'

use_frameworks!

target 'IGColorPicker_Example' do
  pod 'IGColorPicker', :path => '../'
  pod ‘M13Checkbox’, :git => 'https://github.com/andreaantonioni/M13Checkbox.git', :branch => ‘swift-4’

end
